- name: Installing Maven 
  ansible.builtin.yum:
    name: maven
    state: present  

- name: Creating roboshop user account 
  ansible.builtin.include_role:
    name: common
    tasks_from: create-user 

- name: Download and extracting component 
  ansible.builtin.include_role:
    name: common
    tasks_from: download-from-nexus

# **** Uncomment it when you want to donwload from github *****
# - name: Download and extracting frontend 
#   ansible.builtin.include_role:
#     name: common
#     tasks_from: download

# - name: Deleting Old Content
#   ansible.builtin.file:
#     path: /home/roboshop/{{COMPONENT}}
#     state: absent  

# - name: Copy file to destination 
#   ansible.builtin.copy:
#     src:  /tmp/{{COMPONENT}}-main/
#     dest: /home/roboshop/{{COMPONENT}}/
#     remote_src: yes
#   become_user: roboshop 

# - name: Creating artifact
#   ansible.builtin.shell:  mvn clean package && mv target/{{COMPONENT}}-1.0.jar {{COMPONENT}}.jar
#   args:
#     chdir: /home/roboshop/{{COMPONENT}} 
#   become_user: roboshop 

- name: Configuring the service 
  ansible.builtin.include_role:
    name: common
    tasks_from: config-service 

- name: Configuring the rsyslog 
  ansible.builtin.include_role:
    name: elk 
    tasks_from: rsyslog  

- name: Installing the filebeat 
  ansible.builtin.include_role:
    name: elk 
    tasks_from: filebeat  

- name: Installing the NodeExporter  
  ansible.builtin.include_role:
    name: prometheus 
    tasks_from: node-exporter   

- name: Doing set-hostname 
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname